### ISSUE TITLE
Force no-cache

### ISSUE THREAD

**Issue by antonellopasella** [blockchain-certificates/explorer-lookup#264]
Can we provide a way to add an header Cache-Control: max-age=0 in order to disable normal caching from browser for issuer profile and revocation list?

If I revoke a certificate, my viewer correctly show it as revoked but if I revoke a second one (updating the revocation-list.json file) the old cached version is  returned and the second certificate appears good instead of revoked

Can we append an header in XMLHttpRequest like "Cache-Control: max-age=0" or similar in order to force the browser to always re-download a fresh version of external files like revocation list and issuer profile?

If useful I can provide a PR if needed

Thanks

**Comment by antonellopasella** [comment]
@lemoustachiste any thought about this issue?

**Comment by lemoustachiste** [comment]
@antonellopasella sorry I must have missed the initial issue.

Sounds reasonable, I'd like to see it as an API flag: `noCache: boolean`, if enabled then the header gets appended.
If you can work on a PR, please go for it. Otherwise I'll try to get to it when I can.

Thanks

**Comment by antonellopasella** [comment]
@lemoustachiste I'll propose a PR ASAP.

Thanks for the feedback and suggestions

**Comment by antonellopasella** [comment]
> ble, I'd like to see it as an API flag: `noCache: boolean`, if enabled then the header gets appended. If you can work on a PR, please go for it. Otherwise I'll try to get to it when I can.

I'm sorry but I tried to manage a working PR and I'm not able to merge verifier&explorer-lookup in a working local demo.

Would you work on this task? Thanks!

Antonello

**Comment by lemoustachiste** [comment]
I'll get to it soonish

**Comment by lemoustachiste** [comment]
@antonellopasella 

I was doing an initial pass on the problem, and I'm wondering if the issue wouldn't be rather on the server side?
I mean, it seems there are ways to sort of tell the browser to not cache, but it also seems that it does not necessarily always work. ie: https://stackoverflow.com/questions/10927766/force-http-request-to-not-cache

For what it seems, at least from a header perspective, I'm getting `no-cache, no-store` responses in my test cases:


<img width="353" alt="Screenshot 2023-01-18 at 14 36 45" src="https://user-images.githubusercontent.com/12797962/213187785-0b3f24d6-bb0f-4000-9d47-e2c660ea7943.png">

So, with that, would you have an example of document that get cached so that I could experiment with?

Thanks

**Comment by antonellopasella** [comment]
Thanks @lemoustachiste 

You can see the whole package [here](https://kecert.demo.kecert.it/verify/57ff6fbb-89c5-49a3-8aff-1ce358f7551f/) 

We developed [KeCert](https://www.kecert.it) for educational organizations. 
Orgs have a private area where they can invalidate a certificate, but when they test the invalidated certificates, they use the "cached" revocation list without the new ID.

From a security/validation point of view (IMHO) the viewer should never use a cached file, also if the server send cache headers.

Thanks

**Comment by lemoustachiste** [comment]
@antonellopasella it looks like the link you gave me does not work?
Either a 404 or a CORS issue I am not clear:

<img width="488" alt="Screenshot 2023-01-20 at 12 27 28" src="https://user-images.githubusercontent.com/12797962/213684768-16dfd071-4341-45d1-8794-f1197dc37440.png">

**Comment by antonellopasella** [comment]
Can you retry?
This is my current output. There are some issues (in red in console) but the cert is downloaded

Thanks

<img width="859" alt="image" src="https://user-images.githubusercontent.com/96335/214001285-85fb5994-7154-4820-9cc0-4275f75a34fd.png">

**Comment by lemoustachiste** [comment]
Ok so I've got some strange behaviors but by enabling caching from the console I am able to see what I need.

Anyhow, in an [example case](https://blockcerts.learningmachine.com/certificate/5c447c71572d518e9dad57c4e91f9929) I can see that the caching is never happening on the revocation list:

<img width="641" alt="Screenshot 2023-01-23 at 12 39 33" src="https://user-images.githubusercontent.com/12797962/214030843-27be0ad0-f0d2-4ca3-ad62-fa3d14afe20a.png">

The response from your server does not mention anything about `no-cache`:

<img width="483" alt="Screenshot 2023-01-23 at 12 43 29" src="https://user-images.githubusercontent.com/12797962/214031614-6b61c72d-308a-4da8-9696-9e0f66778a01.png">

I will try to see locally if I am able indeed to overwrite this instruction with the request header, but I think it'd be potentially easier to configure the server.

**Comment by lemoustachiste** [comment]
Ok I don't have a strong confidence in the code I have set up as I don't see explicit results.
Somehow the tx data does not get retrieved for this cert (API rate?) so I don't see the revocation list call either.

Anyhow, I have something set up with which I can work, so I'll get on with that and we'll see if that solves the issue for you.

**Comment by lemoustachiste** [comment]
@antonellopasella I have identified some issues with github hosted content, and I suspect it could happen elsewhere.

Basically it looks like a server can reject the request if invalid headers are present. Github denies `Cache-Control` and there is no way to modify this, apparently, so the certs do not validate.

I'm afraid your only solution is to prevent caching on the server-side. I'm going to rollback the release as there is no fit-all workaround and I don't want to go down the path of whitelisting things or not. Sorry.

**Comment by antonellopasella** [comment]
@lemoustachiste  thanks for the update and for your effort.

Only a small note. In the case you provide (github) the solution won't be to disable the no-cache param and not send the header?

The params should be optional (and false by default) and the Cache-Control header will be sent only if provided true

Thanks

**Comment by lemoustachiste** [comment]
> Only a small note. In the case you provide (github) the solution won't be to disable the no-cache param and not send the header?

Yes, but that's unpredictable because you can't know the rules of the target server beforehand, only receive an error.

> The params should be optional (and false by default) and the Cache-Control header will be sent only if provided true
If you do this, where is the entry point in the Blockcerts ecosystem? Is it blockcerts-verifier? cert-verifier-js? explorer-lookup? All of this are valid entry points and they can conflict with each other. I'm all up for flexibility but you cannot predict what cert will be fed into the verifier with consistant rules (ie: maybe the certs for this domain will be ok, but not from the next domain). 

So this has the potential to become a problem for a standard verifier to accept different sources, and you can't turn on the flag on a case by case basis.
